version: "3.9"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
            SA_PASSWORD: "12345Yuiop-"
            ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

  api: 
    build: ./EducationalPortal
    ports:
      - 7105:80
      - 7106:443
    depends_on:
      - "db"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPSPORT=7106
      - ASPNETCORE_Kestrel__Certificates__Default__Password=passw0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - DBConnectionString=server=db;database=EducationalPortal;user=sa;password=12345Yuiop-;TrustServerCertificate=true;
    volumes:
      - ~/.aspnet/https:/https:ro
  
  angular:
    build: ./EducationalPortal.App
    ports:
      - 4200:80
    depends_on:
      - "api"